name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create dependencies directory
        run: |
          mkdir -p fantasy_simulator_lambda/dependencies/python

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r fantasy_simulator_lambda/requirements.txt --target fantasy_simulator_lambda/dependencies/python

      - name: Verify installed dependencies
        run: ls -R fantasy_simulator_lambda/dependencies/python

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Node.js dependencies for Angular app
        working-directory: fantasy_simulator_webapp
        run: |
          npm install
          npm run build --prod

      - name: Verify Angular build output
        run: ls -R fantasy_simulator_webapp/dist

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}" -backend-config="region=${{ secrets.BACKEND_BUCKET_REGION }}" -backend-config="key=${{ secrets.BACKEND_KEY }}"

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Copy Angular build files
        run: |
          mkdir -p terraform/webapp
          cp -r fantasy_simulator_webapp/dist/* terraform/webapp/

      - name: Terraform Plan
        env:
          TF_VAR_aws_region: us-east-1
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        env:
          TF_VAR_aws_region: us-east-1
        run: terraform apply -auto-approve tfplan
